### ISSUE TITLE
[Not real issue] This really worked! Observations.

### ISSUE THREAD

**Issue by FishamanP** [NumesSanguis/naver_line_restore_chat_root#1]
Thank you very much for these scripts! I had a borked data transfer, and was able to make a new data backup and restore messages (with working search!) on Android 14, _without rooting the original or new device_. I did need a third device to root however, but the old device can be reused for this. Letter Sealing was globally disabled on all devices, I'm not sure how that changes the process.

I will refer to the devices as the following:
A - The original LINE device. This device should hold all the data you wish to transfer, but it is okay to be locked out. This device does _not_ need to be rooted. It is possible this device needs to be on Android 12 or under. If you are above Android 12 and rooted, you can copy the database file out directly. I'm sure you're smart enough.
B - A ROOTED middleman device. This can be the same as device A, just make the LINE adb backup before wiping data! Any Android version is okay, I used 14.
C - The target device, already logged into the LINE account but missing past messages. This device does _not_ need to be rooted, and can be running any Android version. I used 14.

Follow these steps:
PC - Download 7-Zip, this repo, DB Browser for SQLite, and a LINE APK older than v5.3. I used v5.1.2.
A - Connect USB debugging to PC and enter these commands:
`adb shell pm uninstall -k jp.naver.line.android`
`adb reboot`
`adb install -r -d c:\line\line-old.apk`
`adb backup -nocompress -f c:\line\line.ab jp.naver.line.android`
PC - open the file `line.ab` in 7-Zip and extract `/apps/jp.naver.line.android/db/naver_line`, the message database. Optionally, extract `/apps/jp.naver.line.android/ef/chats/[hex string]/messages/*`. These are the photos sent in chats. They can be mass-renamed to .JPG files.

--- From this point on, device A is not needed. It can be rooted (wiping data is okay) to become device B. ---

C - Make a Google Drive data backup. Transfer the account to device B using the QR Code process. Restore Drive backup onto B.
B - Use a root file manager to copy out `/data/data/jp.naver.line.android/databases/naver_line` to the PC. Afterward, rename the system file to `naver_line_BAK` or something similar.
PC - Follow this repo's instructions to merge the two databases. (I did not use any of the extra SQL scripts.) Copy the merged database to the same place on B and reboot. (I _did not_ have to change the UID or GID of the new file as indicated in the repo instructions)

--- At this point, device B should have a complete, mostly functional LINE. Message search is broken. Pictures might be able to be injected, but the next step makes this a moot point. ---

B - Make a Google Drive data backup. It is completely normal for the size to be significantly smaller than the PC's db files. Transfer the account to device C using the QR Code process. Restore Drive backup onto C.

--- Now the target Device C should have the complete chat history back, with functional search, just as if a Google Drive backup was done from the start! ---

Thank you very much for your scripts and documentation! **** LINE a million ways.

**Comment by NumesSanguis** [comment]
Thank you for sharing your experience and glad to hear this repo has been useful!
Yeah about **** LINE, I just don't understand why LINE can't have an easy backup for messages...
